### ISSUE TITLE
Nightly installation is failing in jenkins . please fix it 

### ISSUE THREAD

**Issue by tkolhar** [SatelliteQE/automation-tools#189] opened 2015-06-09 14:01 UTC
for rhel6

```
[10.8.29.200] run: katello-installer -d -v --foreman-admin-password="*****" --katello-proxy-url="http://ginger.lab.eng.rdu2.redhat.com" --katello-proxy-port="3128" --katello-proxy-password="r****" --katello-proxy-username="admin" 
[10.8.29.200] out: /bin/bash: katello-installer: command not found
[10.8.29.200] out: 

Fatal error: run() received nonzero return code 127 while executing!

For rhel7
[10.8.30.35] run: usermod -aG dockerroot apache
[10.8.30.35] out: usermod: user 'apache' does not exist
[10.8.30.35] out: 

Fatal error: run() received nonzero return code 6 while executing!

Requested: usermod -aG dockerroot apache
Executed: /bin/bash -l -c "usermod -aG dockerroot apache"
```

**Comment by elyezer** [comment] 2015-06-09 16:43
The apache user probably changed on RHEL 6. I will take a look on this.

**Comment by elyezer** [comment] 2015-06-10 10:13
Actually the issue is on katello-deploy script which nightly job uses. See https://github.com/Katello/katello-deploy/issues/156 for more information.

**Comment by elyezer** [comment] 2015-06-22 19:18
The current failure is not related to automation-tools, closing this.

**Closed by elyezer** 2015-06-22 19:18 UTC
